#!/usr/local/bin/node

let fs = require("fs"); 
let Phrase = require("mhartl-palindrome");
let palindromes = [];    

let text = fs.readFileSync("phrases.txt", "utf-8"); 
text.split("\n").forEach(function(line) {  
   let phrase = new Phrase(line); 
   if (phrase.palindrome()) {  
    console.log("Palindrome detected!", line); 
    palindromes.push(line); 
   } 
});

fs.appendFile("palindromes.txt", palindromes.join("\n"), function (err) {
    if (err) throw err;
    console.log('Saved!');
});