#!/usr/local/bin/node

// Returns the paragraphs from a Wikipedia link, stripped of reference numbers

let request = require("request"); 
let url = process.argv[2]; 

if (!url) {
    console.log("usage: wikp <uri>");
    process.exit();
  }

const jsdom = require("jsdom"); 
const { JSDOM } = jsdom; 

 
request(url, function(error, response, body) {
    let { document } = (new JSDOM(body)).window; 

    // Grab all the paragraphs and references 
    let paragraphs = document.querySelectorAll("p");

    // Grab all elements with the .reference CSS class 
    let references = document.querySelectorAll(".reference");

    // Remove any references. 
    references.forEach(function(reference) {
        reference.remove();   
    }); 

    // Print out all of the paragraphs
    paragraphs.forEach(function(paragraph) {
        console.log(paragraph.textContent);   
    }); 
}); 
  
  